home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

]

magnit/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^root/', admin.site.urls),
    url(r'^', include('home.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

home/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render
from .forms import  UserForm

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'home/login.html')
    else:
     return render(request, 'home/index.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'home/login.html', {"form": form,})


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'home/index.html')
            else:
                return render(request, 'home/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'home/login.html', {'error_message': 'Invalid login'})
    return render(request, 'home/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)

                return render(request, 'home/index.html')
    context = {
        "form": form,
    }
    return render(request, 'home/register.html', context)

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Magnit{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href=""/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'home/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:index' %}">Magnit</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'home:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

home/templates/home/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Magnit{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="#"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900|RobotoDraft:400,100,300,500,700,900'>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'home/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:index' %}">Magnit</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'home:register' %}">Register</a>
                </li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'home:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

home/templates/home/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container">

    <!-- index page -->
    <div class="row">
        <div class="col-sm-12">
            <h3>HI!.. {{ user.username }}</h3>
        </div>
    </div>

</div>
{% endblock %}

home/templates/home/login.html
{% extends 'home/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container">
    <div class="pen-title">
        <h1 class="login-logo">Magnit</h1>
        {% if error_message %}
        <i><strong>{{ error_message }}</strong></i>
        {% endif %}
    </div>
    <!-- Form Module-->
    <div class="module form-module">
        <div class=""><i class="fa fa-times fa-pencil"></i>
{#            <div class="tooltip">Click Me</div>#}
        </div>
        <div class="form">
            <h2>Login to your account</h2>
            <form class="form-horizontal" role="form" action="{% url 'home:login_user'%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text" placeholder="Username" id="id_username" maxlength="30" name="username"/>
                <input type="password" placeholder="Password" id="id_password" maxlength="30" name="password"/>
                <button>Login</button>
            </form>
        </div>
{#        <div class="form">#}
{#            <h2>Create an account</h2>#}
{#            <form>#}
{#                <input type="text" placeholder="Username"/>#}
{#                <input type="password" placeholder="Password"/>#}
{#                <input type="email" placeholder="Email Address"/>#}
{#                <button>Register</button>#}
{#            </form>#}
{#        </div>#}
        <div class="cta"><a href="#">Forgot your password?</a></div>
    </div>
    {% endblock %}

home/templates/home/register.html
{% extends 'home/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
    <div class="container">
    <div class="pen-title">
        <h1 class="login-logo">New Account</h1>
        {% if error_message %}
            <i><strong>{{ error_message }}</strong></i>
        {% endif %}
    </div>
    <!-- Form Module-->
    <div class="module form-module">
        <div class="">
        </div>
        <div class="form">
            <h2>Create an account</h2>
            <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <div class=" col-sm-10">
                            <span class="text-danger small">{{ field.errors }}</span>
                        </div>
                        <div class="col-sm-12"><label class="control-label">{{ field.label_tag }}</label>{{ field }}</div>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">Register</button>
            </form>
        </div>
        <div class="cta"> Already have an account? <a href="{% url 'home:login_user' %} ">Click here</a> to log in.</div>
        <br>
    </div>
{% endblock %}